FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["Docker.Sample.App/Docker.Sample.App.csproj", "Docker.Sample.App/"]
COPY ["Docker.Sample.Core/Docker.Sample.Core.csproj", "Docker.Sample.Core/"]
RUN dotnet restore "Docker.Sample.App/Docker.Sample.App.csproj"
COPY . .
WORKDIR "/src/Docker.Sample.App"
RUN dotnet build "Docker.Sample.App.csproj" --nologo --no-restore -c Release

FROM build AS publish
RUN dotnet publish "Docker.Sample.App.csproj" --nologo --no-build -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Docker.Sample.App.dll"]